name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET for C# projects
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Build C# projects
    - name: Build C# projects
      run: |
        for csproj in $(find assign6_2 -name "*.csproj"); do
          dotnet build "$csproj" --configuration Release
        done

    # Compile Kotlin projects
    - name: Compile Kotlin projects
      run: |
        for ktfile in $(find assign6_2 -name "*.kt"); do
          kotlinc "$ktfile" -include-runtime -d "${ktfile%.kt}.jar"
        done

    # Compile C++ projects
    - name: Compile C++ projects
      run: |
        for cppfile in $(find assign6_2 -name "*.cpp"); do
          g++ "$cppfile" -o "${cppfile%.cpp}"
        done

    # Compile Python scripts
    - name: Compile Python scripts
      run: |
        mkdir -p output/python
        for pyfile in $(find assign6_2 -name "*.py"); do
          py_compile_dir="output/python"
          python3 -m py_compile "$pyfile"
          cp "${pyfile}c" "$py_compile_dir/"
        done

    # Create a zip file of all compiled outputs
    - name: Create release archive
      run: |
        mkdir -p output
        find assign6_2 -type f \( -name "*.dll" -o -name "*.exe" -o -name "*.jar" -o -name "*.out" -o -name "*.pyc" \) -exec cp {} output/ \;
        zip -r release.zip output

    # Create a GitHub release and upload the zip file
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
        body: |
          This release contains the compiled outputs of all projects in assign6_2.
        draft: false
        prerelease: false
        files: release.zip